### PR TITLE
Fixed issue with weather.bash

### PR DESCRIPTION
**Pull request by ertex**
The script saved a temporary file in the local directory, however the target device is read-only so no file go saved.
Changed so the file is stored in /tmp/ instead

### CODE REVIEW

**Comment by mateuszdrwal** [comment]
/tmp on that rpi is for some reason only writeable by root, so that won't work either. i think the working directory is ~ which is read-only, but ~/infosoffa2-slides (the repo root) is mounted as a tempfs so saving temporary files in /home/pi/infosoffa2-slides/ is effectively the same as /tmp

**Comment by ertex** [comment]
So ~/infosoffa2-slides/images should also be writeable? So some other issue should be present.

**Comment by mateuszdrwal** [comment]
should be yes, but you were attempting to write to ~/data_curl.html

**Comment by ertex** [comment]
ah, so it's a issue with code quality as I expected the script to run in the directory it was positioned in.
Will fix this

**Pull request merged**
